### PR TITLE
Fixed Immortals weapon handling in #70

### PR DESCRIPTION
**Pull request by mikeporterdev**
Fixes a minorly annoying issue where BS2TTS doesn't handle Immortals weapon upgrades on the entire unit but rather just one model.

I know pretty much nothing about Haskell so double check all of my work here. 

Thanks!

### CODE REVIEW

**Comment by mikeporterdev** [comment]
@pwestling Anything I can do to help get this one merged?

**Comment by pwestling** [comment]
Hey @mikeporterdev, sorry for the delay - seems like I don't have notifications set up correctly and am only now seeing this after the tag -.- My bad, I will see if we can get this merged

**Comment by pwestling** [comment]
Oh this is great - thanks so much! I'll find time to run the tests on my end just as an extra double check. Should be able to get this merged and deployed later today.

**Comment by pwestling** [comment]
This should be deployed now. Sorry again for all the delays, and thank you so much!

**Pull request merged**
